import { sha256 } from "@cosmjs/crypto";
import { toHex } from "@cosmjs/encoding";

const id = sha256(
  Buffer.from(
    "CsICCvUBCiQvY29zbXdhc20ud2FzbS52MS5Nc2dFeGVjdXRlQ29udHJhY3QSzAEKLG5vbHVzMWtscTI1c254Z2EzM21ncXZyd3J1dXZ2dWxyOTloa3VnYXVxZHNsEkBub2x1czF6a3pybXFrcnN3cnE0MndweHM1ZnZldmQ3Nmh2end3OXY3cngyN3ZhZmtkOHFtZnFyajlzcjlwYzQ3Ggx7InJlcGF5IjpbXX0qTApEaWJjLzdGQkRCRUVFQkE5QzUwQzRCQ0RGN0JGNDM4RUFCOTlFNjQzNjA4MzNEMjQwQjMyNjU1Qzk2RTMxOTU1OUU5MTESBDY5MDUSSExlYXNlIGludGVyZXN0IGNvdmVyZWQgYnkgTm9sdXMhIFRoaXMgb2ZmZXIgcnVucyB1bnRpbCBOb3ZlbWJlciAzMCwgMjAyMxJoClEKRgofL2Nvc21vcy5jcnlwdG8uc2VjcDI1NmsxLlB1YktleRIjCiEDOFvAlcfSrkCnJLhnwWgjprMBnlkPmVKPiJqk6Sf0mqsSBAoCCAEY4gsSEwoNCgR1bmxzEgUxMDAwMBDUiRgaQN7YVNuIeFvFD+YVIrXgeoRXCZ1H4FWS/ITd2ccxwQQ/fekMiOgkNfonTyEsMevR3vMjScavHCoW+f7S2XNZTxE=",
    "base64"
  )
);

console.log(toHex(id).toUpperCase());
