export const TWITTER_ACCOUNT = 'https://twitter.com/NolusPlatform'
export const TELEGRAM_ACCOUNT = 'https://t.me/NolusPlatform'
export const MEDIUM_ACCOUNT = 'https://medium.com/nolusplatform'
export const REDDIT_ACCOUNT = 'https://www.reddit.com/r/NolusPlatform'
export const LINKEDIN_ACCOUNT = 'https://www.linkedin.com/company/nolus-platform'
export const DISCORD_ACCOUNT = 'https://discord.com/invite/Rmwz8S6ZJP'
