export enum RouteNames {
  DASHBOARD = "DASHBOARD",
  AUTH = "AUTH",
  CONNECT_KEPLR = "CONNECT_KEPLR",
  IMPORT_LEDGER = "IMPORT_LEDGER",
  IMPORT_SEED = "IMPORT_SEED",
  SET_PASSWORD = "SET_PASSWORD",
  CREATE_ACCOUNT = "CREATE_ACCOUNT",
  SET_WALLET_NAME = "SET_WALLET_NAME",
  HISTORY = "HISTORY",
  LEASE = "LEASE",
  EARN = "EARN",
  GOOGLE_AUTH = "GOOGLE_AUTH",
}
