export enum WalletActionTypes {
  CONNECT_KEPLR = 'CONNECT_KEPLR',
  CONNECT_LEDGER = 'CONNECT_LEDGER',
  CONNECT_VIA_MNEMONIC = 'CONNECT_VIA_MNEMONIC',
  LOGIN_VIA_TORUS = 'LOGIN_VIA_TORUS',
  TORUS_LOGOUT = 'TORUS_LOGOUT',
  STORE_PRIVATE_KEY = 'STORE_PRIVATE_KEY',
  LOAD_PRIVATE_KEY_AND_SIGN = 'LOAD_PRIVATE_KEY_AND_SIGN',
  UPDATE_BALANCES = 'UPDATE_BALANCES',
  SEARCH_TX = 'SEARCH_TX',
  TRANSFER_TOKENS = 'TRANSFER_TOKENS',
  OPEN_LEASE = 'OPEN_LEASE',
  REPAY_LEASE = 'REPAY_LEASE'
}
