export enum WalletActions {
  CONNECT_KEPLR = "CONNECT_KEPLR",
  CONNECT_LEAP = "CONNECT_LEAP",
  CONNECT_LEDGER = "CONNECT_LEDGER",
  CONNECT_WC = "CONNECT_WC",
  UPDATE_BALANCES = "UPDATE_BALANCES",
  LOAD_VESTED_TOKENS = "LOAD_VESTED_TOKENS",
  LOAD_STAKED_TOKENS = "LOAD_STAKED_TOKENS",
  LOAD_WALLET_NAME = "LOAD_WALLET_NAME",
  LOAD_SUPPLIED_AMOUNT = "LOAD_SUPPLIED_AMOUNT",
  LOAD_APR = "LOAD_APR",
  DISCONNECT = "DISCONNECT"
}
