export enum WalletActions {
  CONNECT_KEPLR = "CONNECT_KEPLR",
  CONNECT_LEAP = "CONNECT_LEAP",
  CONNECT_LEDGER = "CONNECT_LEDGER",
  CONNECT_WC = "CONNECT_WC",
  CONNECT_EVM_METAMASK = "CONNECT_EVM_METAMASK",
  CONNECT_EVM_PHANTOM = "CONNECT_EVM_PHANTOM",
  CONNECT_SOL_SOLFLARE = "CONNECT_SOL_SOLFLARE",

  LOAD_VESTED_TOKENS = "LOAD_VESTED_TOKENS",
  LOAD_WALLET_NAME = "LOAD_WALLET_NAME",
  LOAD_APR = "LOAD_APR",
  DISCONNECT = "DISCONNECT"
}
