export enum WalletActionTypes {
  CONNECT_GOOGLE = 'CONNECT_GOOGLE',
  CONNECT_KEPLR = 'CONNECT_KEPLR',
  CONNECT_LEDGER = 'CONNECT_LEDGER',
  CONNECT_VIA_MNEMONIC = 'CONNECT_VIA_MNEMONIC',
  STORE_PRIVATE_KEY = 'STORE_PRIVATE_KEY',
  LOAD_PRIVATE_KEY_AND_SIGN = 'LOAD_PRIVATE_KEY_AND_SIGN',
  UPDATE_BALANCES = 'UPDATE_BALANCES',
  SEARCH_TX = 'SEARCH_TX',
  LOAD_VESTED_TOKENS = 'LOAD_VESTED_TOKENS',
  LOAD_STAKED_TOKENS = 'LOAD_STAKED_TOKENS',
  LOAD_WALLET_NAME = 'LOAD_WALLET_NAME',
}
