name: Deploy dev

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-dev
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      deploy_dir: /opt/deploy/builds/app-dev
      service: webapp-dev
      health_port: 5050
      base_domain: app-dev.nolus.io
    secrets:
      IBC_SOLRAY_DEPLOY_KEY: ${{ secrets.IBC_SOLRAY_DEPLOY_KEY }}
