name: Deploy prod

on:
  push:
    tags:
      - v*.*.*

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      deploy_dir: /opt/deploy/builds/app
      service: webapp-prod
      health_port: 5051
      base_domain: app.nolus.io
